version: '3.7'

services:
  gemini_prod:
    container_name: gemini_prod
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        nodata:
    volumes:
      - ..:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - ma

networks:
  ma:
    external: true