FROM nginx:1.15

ADD nginx/ /etc/nginx/conf.d
ADD nginx/nginx.conf /etc/nginx/nginx.conf:ro
ADD ./gemini_gui.zip /

RUN apt-get update
RUN apt-get -y install zip
RUN unzip /gemini_gui.zip -d /
RUN cp -R /dist/* /usr/share/nginx/html

CMD bash -c 'cd /etc/nginx/conf.d/ && ./nginx_start.sh'